baseURL = "https://maxscame.github.io/"
title = "scame@blog~"
copyright = "Maxim N."
theme = "archie"

# Code Highlight
pygmentsstyle = "solarized-dark256"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[markup.goldmark.renderer]
unsafe= true

[params]
    mode="dark" # color-mode light,dark or auto
    featherIconsCDN=true
    subtitle = "DSP C++ Software Engineer📡"


# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/MaxScame"


[[params.social]]
name = "Telegram"
icon = "message-square"
url = "https://t.me/outside_space"


DefaultContentLanguage = "ru"


[languages]
  [languages.ru]
    languageName = "Русский"
    title = "scame@ru_blog~"
    subtitle = "Пишу всякий софт для георадаров📡"
    copyright = "Максим Н."
    weight = 2
    contentDir = "content/ru"

  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"



# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3